// This file is automatically generated.  DO NOT EDIT

<<<<<<< HEAD
#define CUDPP_APP_DATA_DIR  "D:/PROJECTS/gvdb-voxels/source/shared_cudpp/apps/data/"
=======
#define CUDPP_APP_DATA_DIR  "D:/Codes/gvdb-voxels/source/shared_cudpp/apps/data/"
>>>>>>> upstream/master
